info:
  app:
    name: reporting-be

server:
  port: 30027

logging:
  level:
    com:
      cema: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
app:
  region: AR

spring:
  profiles:
    active: local
  application:
    name: reporting-be
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/reporting
    username: reporting
    password: p!JR39u&Za*^&Dbb
back-end:
  users:
    url: "http://localhost:30023/v1/users"

---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.5:5432/reporting
  config:
    activate:
      on-profile: qa
back-end:
  users:
    url: "http://192.168.100.5:30023/v1/users"

---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.6:5432/reporting
  config:
    activate:
      on-profile: prod
back-end:
  users:
    url: "http://192.168.100.6:30023/v1/users"
